"""allow course to be publish

Revision ID: fdee2b9fc879
Revises: 3c4c8e8f2190
Create Date: 2022-12-16 23:55:27.036533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdee2b9fc879'
down_revision = '3c4c8e8f2190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
